import { DocumentSample, FacelockSample, VoiceProfileSample } from "./types";

export const BANKING_DOCUMENT_SAMPLES: DocumentSample[] = [
  {
    id: "pan-org-1",
    name: "PAN Card (Amit Verma)",
    documentType: "PAN Card",
    category: "Organic (Verify)",
    description: "Authentic physical Indian Permanent Account Number card. Displays clean micro-printing, embossed title, and 3D hologram sticker with correct visual diffraction vectors.",
    imagePlaceholder: "bg-emerald-950/10 border-emerald-500/20 text-emerald-400",
    indicatorList: [
      "Micro-font text on boundary is high resolution",
      "Authentic Holographic emblem integrity verified",
      "Exact geometric PAN font alignment matched",
      "Watermark texture patterns consistent with physical stock"
    ],
    simulatedAnomalies: [],
    isSynthetic: false
  },
  {
    id: "pan-fake-1",
    name: "PAN Card (Amit Verma - AI Doctored)",
    documentType: "PAN Card",
    category: "Synthetic / Fabricated (Alert)",
    description: "Deep-learning fabricated PAN. Synthetically superimposed photograph. Displays subtle kerning inconsistencies on legal text, and minor edge bleeding near the border outline.",
    imagePlaceholder: "bg-red-950/10 border-red-500/20 text-red-400",
    indicatorList: [
      "Typographical font mismatch on card identifier label",
      "Photo boundary shows pixel bleeding and digital superimposition margins",
      "Emblem lacks 3D holographic diffraction properties",
      "QR code is low contrast with blurred edge artifacts"
    ],
    simulatedAnomalies: [
      "Border alignment mismatch",
      "Overlay font anomalies",
      "Emblem flatness",
      "Artificial QR blur"
    ],
    isSynthetic: true
  },
  {
    id: "aadhaar-org-1",
    name: "Aadhaar Card (Priya Nair)",
    documentType: "Aadhaar Card",
    category: "Organic (Verify)",
    description: "Official Aadhaar Card with clear Government of India insignia, valid secure QR code, sharp microprinting profiles, and correct biometric photograph boundaries.",
    imagePlaceholder: "bg-emerald-950/10 border-emerald-500/20 text-emerald-400",
    indicatorList: [
      "High resolution Ashoka Pillar emblem rendering",
      "Sharp and scannable Aadhaar QR code bounds",
      "Standard Indian Flag tricolor gradient matches regulatory format",
      "Dual language Hindi-English typesetting is perfectly aligned"
    ],
    simulatedAnomalies: [],
    isSynthetic: false
  },
  {
    id: "aadhaar-fake-1",
    name: "Aadhaar Card (Priya Nair - Gen-AI Fabricated)",
    documentType: "Aadhaar Card",
    category: "Synthetic / Fabricated (Alert)",
    description: "This document is generated by an open-source generative model. Typographic analysis flags a font face replacement in Hindi scripting, and visual alignment has minor angle deviations.",
    imagePlaceholder: "bg-red-950/10 border-red-500/20 text-red-400",
    indicatorList: [
      "Hindi typesetting uses non-standard digital-printing glyphs",
      "Moiré patterns suggest capture from an LCD monitor replay attack",
      "Minor pixel overlap near the security border outline",
      "QR code is statically hardcoded with dead metadata routing"
    ],
    simulatedAnomalies: [
      "Hindi typographical discrepancy",
      "Boundary pixel overlap",
      "Dead QR routing",
      "Static emblem replication"
    ],
    isSynthetic: true
  }
];

export const FACELOCK_SAMPLES: FacelockSample[] = [
  {
    id: "face-org-1",
    name: "Karan Johar (Onboarding Customer)",
    category: "Organic Biometric",
    description: "Authentic, live-captured onboarding selfie video frame. Natural lighting with physiological dual pupil reflections, proper skin tissue micro-texture, and synchronized head posture.",
    imagePlaceholder: "border-emerald-500/30 text-emerald-400",
    indicatorList: [
      "Physiological dual corneal reflections match light-vector",
      "Micro-vessel pulse signals present within skin-tone analysis",
      "Perfect boundary cohesion around jaw and earlobes"
    ],
    simulatedAnomalies: [],
    isSynthetic: false
  },
  {
    id: "face-fake-1",
    name: "Karan Johar (Real-Time Deepfake Injection)",
    category: "Deepfake Generative",
    description: "Synthesized using a real-time Generative Adversarial Network (GAN). Features high facial smoothing, static gaze (pupils fail to track challenges), and feathering residues around the ears.",
    imagePlaceholder: "border-red-500/30 text-red-400",
    indicatorList: [
      "No dual pupil reflection tracking; static gaze vector detected",
      "Feathering artifacts and color bleeding on jaw-neck interface",
      "High skin-smoothing coefficient lacks pore structures",
      "Abnormal visual artifacts during ocular challenge rotations"
    ],
    simulatedAnomalies: [
      "Ocular glaze",
      "Blending residue",
      "Texture flatness",
      "Challenge-response latency"
    ],
    isSynthetic: true
  }
];

export const VOICE_SAMPLES: VoiceProfileSample[] = [
  {
    id: "voice-org-1",
    name: "SBI Service Desk (Organic Agent)",
    category: "Organic Sound Spectrum",
    description: "RecordedSBI banking representative verification agent. Natural conversational flow, physiological inhalation gaps, background environmental room noise, and organic harmonic tremor.",
    frequencyRange: "100Hz - 3400Hz",
    isSynthetic: false
  },
  {
    id: "voice-fake-1",
    name: "SBI Service Desk (AI Synthesized Voice)",
    category: "AI Voice Clone",
    description: "Low-latency voice clone synthesized using current text-to-speech vocoders. Continuous sound energy without respiration breaks, repetitive F0 micro-structure, and stationary noise footprint.",
    frequencyRange: "75Hz - 4200Hz",
    isSynthetic: true
  }
];
